//! Semantic diff engine for IFC graphs.
//!
//! # Matching strategy
//!
//! Entity identity in IFC is unstable across re-exports: STEP `#N` ids are
//! reassigned every time, and `GlobalId` may be regenerated by some tools.
//! We therefore match in three cascading layers:
//!
//! 1. **`GlobalId`**  — strongest; preferred when available.
//! 2. **Canonical Merkle hash** — identifies isomorphic subgraphs even when
//!    `GlobalIds` churn.
//! 3. **(type, slot-position)** fallback — phase 3 work; today we report
//!    unmatched-GlobalId nodes as `Added` / `Removed`.
//!
//! # Change model
//!
//! Output is a [`DiffReport`] containing [`Change`] records. Each change is
//! tagged with a [`Layer`] (Property / Relationship / Shape) so renderers and
//! merge logic can weight them differently.

use std::collections::BTreeMap;
use std::fmt::Write;

use ahash::{AHashMap, AHashSet};
use serde::{Deserialize, Serialize};

pub mod merge;

pub use merge::{merge_graphs, render_merge_text, Conflict, MergeOp, MergeResult, Side};

use vex_graph::{hash_graph, HashConfig, IfcGraph, Node, NodeId, Value};
use vex_utils::{Hash256, StringInterner};

/// Which semantic layer a change occupies. Drives rendering + merge rules.
/// Serialized `snake_case` (`property` / `relationship` / `shape`) — part of
/// the `vex.visual-diff/1` public schema via `ElementChange::layer`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Layer {
    Property,
    Relationship,
    Shape,
}

/// A property-level delta on a matched node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropDelta {
    pub key: String,
    pub before: Option<SerValue>,
    pub after: Option<SerValue>,
}

/// Cartesian location delta resolved from a product's `ObjectPlacement`
/// chain (`IfcLocalPlacement → IfcAxis2Placement3D → IfcCartesianPoint`).
/// Coordinates are the *local* placement location — relative-placement
/// composition is future work — which is exactly what changes when a user
/// moves an element in their CAD tool.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlacementDelta {
    pub before: Option<[f64; 3]>,
    pub after: Option<[f64; 3]>,
}

/// Self-contained serialized value — mirrors `vex_graph::Value` but with all
/// strings resolved, so diff reports are portable and render-friendly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SerValue {
    Null,
    Bool(bool),
    Int(i64),
    Real(f64),
    Text(String),
    Enum(String),
    List(Vec<SerValue>),
    Typed { name: String, inner: Box<SerValue> },
}

/// A single semantic change between two models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Change {
    Added {
        identity: Identity,
        type_name: String,
    },
    Removed {
        identity: Identity,
        type_name: String,
    },
    Modified {
        identity: Identity,
        type_name: String,
        deltas: Vec<PropDelta>,
        layer: Layer,
        /// Location change when the element's placement moved. Present only
        /// when the resolved placement location differs beyond tolerance.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        placement: Option<PlacementDelta>,
    },
}

/// How we identified a given matched (or unmatched) node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Identity {
    GlobalId(String),
    StructuralHash(String),
    StepId(u64),
}

/// Aggregate report from a diff run.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiffReport {
    pub changes: Vec<Change>,
    pub summary: DiffSummary,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiffSummary {
    pub added: u32,
    pub removed: u32,
    pub modified: u32,
}

/// Compute a semantic diff between two IFC graphs.
///
/// `interner_a` and `interner_b` may be separate interner instances — this is
/// the common case since two models are parsed independently. The diff
/// resolves all interned strings internally.
pub fn diff(
    a: &IfcGraph,
    interner_a: &StringInterner,
    b: &IfcGraph,
    interner_b: &StringInterner,
    cfg: &HashConfig,
) -> DiffReport {
    let ha = hash_graph(a, interner_a, cfg);
    let hb = hash_graph(b, interner_b, cfg);

    // Build GlobalId indexes.
    let idx_by_guid_a = index_by_global_id(a);
    let idx_by_guid_b = index_by_global_id(b);

    let mut matched_a: AHashSet<NodeId> = AHashSet::with_capacity(a.node_count());
    let mut matched_b: AHashSet<NodeId> = AHashSet::with_capacity(b.node_count());
    let mut changes: Vec<Change> = Vec::new();
    let mut summary = DiffSummary::default();

    // === Pass 1: match by GlobalId ===
    let geom_a = GeomIndex::new(a, interner_a, &ha, &cfg.tolerance);
    let geom_b = GeomIndex::new(b, interner_b, &hb, &cfg.tolerance);
    for (guid, &id_a) in &idx_by_guid_a {
        if let Some(&id_b) = idx_by_guid_b.get(guid) {
            matched_a.insert(id_a);
            matched_b.insert(id_b);
            if ha.per_node[&id_a] == hb.per_node[&id_b] {
                continue;
            }
            let node_a = &a.nodes[id_a];
            let node_b = &b.nodes[id_b];
            let deltas = diff_properties(node_a, interner_a, node_b, interner_b);
            let placement = placement_delta(&geom_a, id_a, &geom_b, id_b);
            let shape_changed = geom_a.fingerprint(id_a) != geom_b.fingerprint(id_b);
            let layer = if shape_changed {
                Layer::Shape
            } else if deltas.is_empty() {
                Layer::Relationship
            } else {
                Layer::Property
            };
            changes.push(Change::Modified {
                identity: Identity::GlobalId(guid.clone()),
                type_name: interner_b.resolve(node_b.type_name).to_string(),
                deltas,
                layer,
                placement,
            });
            summary.modified += 1;
        }
    }

    // === Pass 2: match by exact structural hash (multiset) ===
    // Anonymous sub-entities are routinely duplicated in real exports (every
    // wall referencing an identical profile / cartesian point). Hash matching
    // must therefore pair *multisets*: k identical nodes on each side match
    // k-for-k in deterministic (insertion) order; any surplus stays unmatched.
    let mut by_hash_a: AHashMap<Hash256, Vec<NodeId>> = AHashMap::new();
    for (id, _) in &a.nodes {
        if !matched_a.contains(&id) {
            by_hash_a.entry(ha.per_node[&id]).or_default().push(id);
        }
    }
    let mut by_hash_b: AHashMap<Hash256, Vec<NodeId>> = AHashMap::new();
    for (id, _) in &b.nodes {
        if !matched_b.contains(&id) {
            by_hash_b.entry(hb.per_node[&id]).or_default().push(id);
        }
    }
    for (h, ids_a) in &by_hash_a {
        if let Some(ids_b) = by_hash_b.get(h) {
            for (ia, ib) in ids_a.iter().zip(ids_b.iter()) {
                matched_a.insert(*ia);
                matched_b.insert(*ib);
            }
        }
    }

    // === Pass 3: report unmatched ===
    for (id, node) in &a.nodes {
        if !matched_a.contains(&id) {
            changes.push(Change::Removed {
                identity: best_identity(node, ha.per_node[&id]),
                type_name: interner_a.resolve(node.type_name).to_string(),
            });
            summary.removed += 1;
        }
    }
    for (id, node) in &b.nodes {
        if !matched_b.contains(&id) {
            changes.push(Change::Added {
                identity: best_identity(node, hb.per_node[&id]),
                type_name: interner_b.resolve(node.type_name).to_string(),
            });
            summary.added += 1;
        }
    }

    changes.sort_by_key(change_sort_key);

    DiffReport { changes, summary }
}

fn index_by_global_id(g: &IfcGraph) -> AHashMap<String, NodeId> {
    let mut out = AHashMap::with_capacity(g.node_count());
    for (id, node) in &g.nodes {
        if let Some(gid) = &node.global_id {
            out.insert(gid.0.clone(), id);
        }
    }
    out
}

/// Max BFS depth when collecting a node's reachable geometry hashes. Product
/// shape chains are shallow (product → shape → representation → item ≈ 4);
/// the cap keeps the walk local instead of crawling spatial containment.
const GEOM_BFS_DEPTH: usize = 8;

/// Per-side adjacency + geometry lookup used for shape attribution and
/// placement resolution.
struct GeomIndex<'g> {
    graph: &'g IfcGraph,
    out: AHashMap<NodeId, Vec<&'g vex_graph::ir::Edge>>,
    geometry: &'g AHashMap<NodeId, Hash256>,
    interner: &'g StringInterner,
    tol: vex_utils::Tolerance,
}

impl<'g> GeomIndex<'g> {
    fn new(
        graph: &'g IfcGraph,
        interner: &'g StringInterner,
        hashes: &'g vex_graph::GraphHashes,
        tol: &vex_utils::Tolerance,
    ) -> Self {
        let mut out: AHashMap<NodeId, Vec<&vex_graph::ir::Edge>> =
            AHashMap::with_capacity(graph.node_count());
        for e in &graph.edges {
            out.entry(e.from).or_default().push(e);
        }
        for v in out.values_mut() {
            v.sort_by_key(|e| (e.slot, e.list_index));
        }
        Self {
            graph,
            out,
            geometry: &hashes.geometry,
            interner,
            tol: *tol,
        }
    }

    fn edges(&self, id: NodeId) -> &[&'g vex_graph::ir::Edge] {
        self.out.get(&id).map_or(&[], Vec::as_slice)
    }

    fn type_of(&self, id: NodeId) -> String {
        self.graph
            .nodes
            .get(id)
            .map(|n| self.interner.resolve(n.type_name).to_ascii_uppercase())
            .unwrap_or_default()
    }

    /// Sorted multiset hash of all geometry hashes reachable from `id` via
    /// outgoing edges (bounded BFS). `Hash256::ZERO` when no geometry is
    /// reachable — two zero fingerprints compare equal, which is correct:
    /// no shape on either side means no shape change.
    fn fingerprint(&self, id: NodeId) -> Hash256 {
        let mut collected: Vec<[u8; 32]> = Vec::new();
        let mut visited: AHashSet<NodeId> = AHashSet::new();
        let mut frontier = vec![id];
        visited.insert(id);
        for _ in 0..=GEOM_BFS_DEPTH {
            if frontier.is_empty() {
                break;
            }
            let mut next = Vec::new();
            for n in frontier.drain(..) {
                if let Some(h) = self.geometry.get(&n) {
                    collected.push(*h.as_bytes());
                }
                for e in self.edges(n) {
                    if visited.insert(e.to) {
                        next.push(e.to);
                    }
                }
            }
            frontier = next;
        }
        if collected.is_empty() {
            return Hash256::ZERO;
        }
        collected.sort_unstable();
        let mut h = vex_utils::Hasher::new(vex_utils::hash::HashAlgo::Blake3);
        h.update(b"geomfp:");
        h.update(&(collected.len() as u64).to_be_bytes());
        for c in &collected {
            h.update(c);
        }
        h.finalize()
    }

    /// Resolve a product's local placement location:
    /// product —slot 5→ `IfcLocalPlacement` —slot 1→ `IfcAxis2Placement3D`
    /// —slot 0→ `IfcCartesianPoint(Coordinates)`.
    fn placement_location(&self, id: NodeId) -> Option<[f64; 3]> {
        let placement = self
            .edges(id)
            .iter()
            .find(|e| e.slot == 5)
            .map(|e| e.to)
            .filter(|p| self.type_of(*p) == "IFCLOCALPLACEMENT")?;
        // IfcLocalPlacement(PlacementRelTo, RelativePlacement)
        let axis = self
            .edges(placement)
            .iter()
            .find(|e| e.slot == 1)
            .map(|e| e.to)?;
        // IfcAxis2Placement3D(Location, Axis, RefDirection)
        let point = self
            .edges(axis)
            .iter()
            .find(|e| e.slot == 0)
            .map(|e| e.to)
            .filter(|p| self.type_of(*p) == "IFCCARTESIANPOINT")?;
        let node = self.graph.nodes.get(point)?;
        let (_, v) = node.props.first()?;
        let Value::List(xs) = v else { return None };
        let mut coords = [0.0f64; 3];
        for (i, c) in coords.iter_mut().enumerate() {
            *c = match xs.get(i) {
                Some(Value::Real(x)) => *x,
                Some(Value::Int(n)) => *n as f64,
                None if i == 2 => 0.0,
                _ => return None,
            };
        }
        Some(coords)
    }

    fn quantized(&self, p: [f64; 3]) -> [f64; 3] {
        p.map(|c| self.tol.quantize_linear(c))
    }
}

/// Compare placement locations across two matched nodes; `Some` only when
/// they differ beyond tolerance. Reported coordinates are the raw source
/// values (display-friendly); the equality check uses quantized values so
/// exporter float noise below tolerance never reports a move.
fn placement_delta(
    ga: &GeomIndex<'_>,
    id_a: NodeId,
    gb: &GeomIndex<'_>,
    id_b: NodeId,
) -> Option<PlacementDelta> {
    let before = ga.placement_location(id_a);
    let after = gb.placement_location(id_b);
    let qb = before.map(|p| ga.quantized(p));
    let qa = after.map(|p| gb.quantized(p));
    if qb == qa {
        return None;
    }
    Some(PlacementDelta { before, after })
}

fn best_identity(node: &Node, hash: Hash256) -> Identity {
    if let Some(g) = &node.global_id {
        Identity::GlobalId(g.0.clone())
    } else if hash != Hash256::ZERO {
        Identity::StructuralHash(hash.to_hex())
    } else {
        Identity::StepId(node.step_id)
    }
}

fn diff_properties(a: &Node, ia: &StringInterner, b: &Node, ib: &StringInterner) -> Vec<PropDelta> {
    let mut map_a: BTreeMap<String, &Value> = BTreeMap::new();
    for (k, v) in &a.props {
        map_a.insert(ia.resolve(*k).to_string(), v);
    }
    let mut map_b: BTreeMap<String, &Value> = BTreeMap::new();
    for (k, v) in &b.props {
        map_b.insert(ib.resolve(*k).to_string(), v);
    }

    let mut all_keys: AHashSet<String> = AHashSet::new();
    for k in map_a.keys() {
        all_keys.insert(k.clone());
    }
    for k in map_b.keys() {
        all_keys.insert(k.clone());
    }
    let mut keys: Vec<String> = all_keys.into_iter().collect();
    keys.sort();

    let mut out = Vec::new();
    for k in keys {
        let va = map_a.get(&k).copied();
        let vb = map_b.get(&k).copied();
        match (va, vb) {
            (Some(x), Some(y)) => {
                let rx = resolve(x, ia);
                let ry = resolve(y, ib);
                if rx != ry {
                    out.push(PropDelta {
                        key: k,
                        before: Some(rx),
                        after: Some(ry),
                    });
                }
            }
            (Some(x), None) => out.push(PropDelta {
                key: k,
                before: Some(resolve(x, ia)),
                after: None,
            }),
            (None, Some(y)) => out.push(PropDelta {
                key: k,
                before: None,
                after: Some(resolve(y, ib)),
            }),
            (None, None) => unreachable!(),
        }
    }
    out
}

pub(crate) fn resolve(v: &Value, i: &StringInterner) -> SerValue {
    match v {
        Value::Null => SerValue::Null,
        Value::Bool(b) => SerValue::Bool(*b),
        Value::Int(n) => SerValue::Int(*n),
        Value::Real(x) => SerValue::Real(*x),
        Value::Text(s) => SerValue::Text(i.resolve(*s).to_string()),
        Value::Enum(s) => SerValue::Enum(i.resolve(*s).to_string()),
        Value::List(xs) => SerValue::List(xs.iter().map(|x| resolve(x, i)).collect()),
        Value::Typed { name, inner } => SerValue::Typed {
            name: i.resolve(*name).to_string(),
            inner: Box::new(resolve(inner, i)),
        },
    }
}

fn change_sort_key(c: &Change) -> (u8, String) {
    let (order, id) = match c {
        Change::Removed { identity, .. } => (0, identity_key(identity)),
        Change::Modified { identity, .. } => (1, identity_key(identity)),
        Change::Added { identity, .. } => (2, identity_key(identity)),
    };
    (order, id)
}

fn identity_key(id: &Identity) -> String {
    match id {
        Identity::GlobalId(s) => format!("G:{s}"),
        Identity::StructuralHash(s) => format!("H:{s}"),
        Identity::StepId(n) => format!("S:{n}"),
    }
}

/// Convenience renderer producing Git-style human-readable output.
pub fn render_text(report: &DiffReport) -> String {
    let mut out = String::new();
    for c in &report.changes {
        match c {
            Change::Added {
                identity,
                type_name,
            } => {
                let _ = writeln!(out, "+ {type_name} {}", identity_text(identity));
            }
            Change::Removed {
                identity,
                type_name,
            } => {
                let _ = writeln!(out, "- {type_name} {}", identity_text(identity));
            }
            Change::Modified {
                identity,
                type_name,
                deltas,
                layer,
                placement,
            } => {
                let _ = writeln!(out, "~ {type_name} {} [{layer:?}]", identity_text(identity));
                if let Some(p) = placement {
                    let _ = writeln!(
                        out,
                        "    placement : {} -> {}",
                        fmt_point(p.before.as_ref()),
                        fmt_point(p.after.as_ref())
                    );
                }
                for d in deltas {
                    let _ = writeln!(out, "    {} : {:?} -> {:?}", d.key, d.before, d.after);
                }
            }
        }
    }
    let _ = writeln!(
        out,
        "\n{} added, {} removed, {} modified",
        report.summary.added, report.summary.removed, report.summary.modified
    );
    out
}

fn identity_text(id: &Identity) -> String {
    match id {
        Identity::GlobalId(s) => format!("GlobalId={s}"),
        Identity::StructuralHash(s) => format!("Hash={}", &s[..16.min(s.len())]),
        Identity::StepId(n) => format!("#{n}"),
    }
}

fn fmt_point(p: Option<&[f64; 3]>) -> String {
    match p {
        Some([x, y, z]) => format!("({x}, {y}, {z})"),
        None => "∅".to_string(),
    }
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use std::io::Cursor;
    use vex_graph::GraphBuilder;
    use vex_ifc_parser::{ParseLimits, Parser};

    fn build(src: &str) -> (IfcGraph, StringInterner) {
        let i = StringInterner::new();
        let mut p = Parser::new(Cursor::new(src), ParseLimits::default());
        let g = GraphBuilder::build_from_parser(i.clone(), &mut p).expect("build");
        (g, i)
    }

    const BASE: &str = "\
ISO-10303-21;
HEADER; FILE_DESCRIPTION((''),'2;1'); FILE_NAME('','',(''),(''),'','',''); FILE_SCHEMA(('IFC4')); ENDSEC;
DATA;
#1 = IFCPROJECT('0YvctVUKr0kugbFTf53O9L',$,'Project',$,$,$,$,$,$);
#2 = IFCWALL('2O2Fr$t4X7Zf8NOew3FNr2',$,'Wall-1',$,$,$,$,$,.STANDARD.);
ENDSEC;
END-ISO-10303-21;
";

    #[test]
    fn no_changes_on_identical() {
        let (a, ia) = build(BASE);
        let (b, ib) = build(BASE);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.changes.len(), 0);
    }

    #[test]
    fn detects_property_change() {
        let (a, ia) = build(BASE);
        let mutated = BASE.replace("'Wall-1'", "'Wall-2'");
        let (b, ib) = build(&mutated);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.summary.modified, 1);
        assert_eq!(r.summary.added, 0);
        assert_eq!(r.summary.removed, 0);
    }

    #[test]
    fn detects_addition() {
        let (a, ia) = build(BASE);
        let added = BASE.replace(
            "ENDSEC;\nEND-ISO-10303-21;",
            "#3 = IFCSLAB('3O2Fr$t4X7Zf8NOew3FNr3',$,'Slab',$,$,$,$,$,.FLOOR.);\nENDSEC;\nEND-ISO-10303-21;",
        );
        let (b, ib) = build(&added);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.summary.added, 1);
        assert_eq!(r.summary.removed, 0);
    }

    const PLACED_WALL: &str = "\
ISO-10303-21;
HEADER; FILE_DESCRIPTION((''),'2;1'); FILE_NAME('','',(''),(''),'','',''); FILE_SCHEMA(('IFC4')); ENDSEC;
DATA;
#1 = IFCCARTESIANPOINT((0.0, 0.0, 0.0));
#2 = IFCAXIS2PLACEMENT3D(#1, $, $);
#3 = IFCLOCALPLACEMENT($, #2);
#4 = IFCWALL('2O2Fr$t4X7Zf8NOew3FNr2',$,'Wall-1',$,$,#3,$,$,.STANDARD.);
ENDSEC;
END-ISO-10303-21;
";

    #[test]
    fn moved_wall_yields_placement_delta() {
        let (a, ia) = build(PLACED_WALL);
        let moved = PLACED_WALL.replace("((0.0, 0.0, 0.0))", "((0.2, 0.0, 0.0))");
        let (b, ib) = build(&moved);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.summary.modified, 1, "changes: {:?}", r.changes);
        let m = r
            .changes
            .iter()
            .find_map(|c| match c {
                Change::Modified {
                    placement: Some(p), ..
                } => Some(p.clone()),
                _ => None,
            })
            .expect("placement delta on the wall");
        assert_eq!(m.before, Some([0.0, 0.0, 0.0]));
        assert_eq!(m.after, Some([0.2, 0.0, 0.0]));
    }

    const MESH_WALL: &str = "\
ISO-10303-21;
HEADER; FILE_DESCRIPTION((''),'2;1'); FILE_NAME('','',(''),(''),'','',''); FILE_SCHEMA(('IFC4')); ENDSEC;
DATA;
#1 = IFCCARTESIANPOINTLIST3D(((0.0,0.0,0.0),(1.0,0.0,0.0),(1.0,1.0,0.0),(0.0,1.0,0.0)));
#2 = IFCTRIANGULATEDFACESET(#1, $, .T., ((1,2,3),(1,3,4)), $);
#3 = IFCSHAPEREPRESENTATION($, 'Body', 'Tessellation', (#2));
#4 = IFCPRODUCTDEFINITIONSHAPE($, $, (#3));
#5 = IFCWALL('2O2Fr$t4X7Zf8NOew3FNr2',$,'Wall-1',$,$,$,#4,$,.STANDARD.);
ENDSEC;
END-ISO-10303-21;
";

    #[test]
    fn mesh_edit_classified_as_shape_layer() {
        let (a, ia) = build(MESH_WALL);
        let edited = MESH_WALL.replace("(1.0,1.0,0.0)", "(1.0,1.4,0.0)");
        let (b, ib) = build(&edited);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        let wall = r
            .changes
            .iter()
            .find(|c| {
                matches!(
                    c,
                    Change::Modified {
                        identity: Identity::GlobalId(_),
                        ..
                    }
                )
            })
            .expect("wall modified");
        let Change::Modified { layer, .. } = wall else {
            unreachable!()
        };
        assert_eq!(*layer, Layer::Shape);
    }

    #[test]
    fn rename_still_property_layer_with_mesh_present() {
        let (a, ia) = build(MESH_WALL);
        let renamed = MESH_WALL.replace("'Wall-1'", "'Wall-2'");
        let (b, ib) = build(&renamed);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        let Change::Modified { layer, .. } = &r.changes[0] else {
            panic!("expected modified, got {:?}", r.changes)
        };
        assert_eq!(
            *layer,
            Layer::Property,
            "unchanged mesh must not trip Shape"
        );
    }
}
