//! Semantic diff engine for IFC graphs.
//!
//! # Matching strategy
//!
//! Entity identity in IFC is unstable across re-exports: STEP `#N` ids are
//! reassigned every time, and `GlobalId` may be regenerated by some tools.
//! We therefore match in three cascading layers:
//!
//! 1. **`GlobalId`**  — strongest; preferred when available.
//! 2. **Canonical Merkle hash** — identifies isomorphic subgraphs even when
//!    `GlobalIds` churn.
//! 3. **(type, slot-position)** fallback — phase 3 work; today we report
//!    unmatched-GlobalId nodes as `Added` / `Removed`.
//!
//! # Change model
//!
//! Output is a [`DiffReport`] containing [`Change`] records. Each change is
//! tagged with a [`Layer`] (Property / Relationship / Shape) so renderers and
//! merge logic can weight them differently.

use std::collections::BTreeMap;
use std::fmt::Write;

use ahash::{AHashMap, AHashSet};
use serde::{Deserialize, Serialize};

pub mod merge;

pub use merge::{merge_graphs, render_merge_text, Conflict, MergeOp, MergeResult, Side};

use vex_graph::{hash_graph, HashConfig, IfcGraph, Node, NodeId, Value};
use vex_utils::{Hash256, StringInterner};

/// Which semantic layer a change occupies. Drives rendering + merge rules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Layer {
    Property,
    Relationship,
    Shape,
}

/// A property-level delta on a matched node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropDelta {
    pub key: String,
    pub before: Option<SerValue>,
    pub after: Option<SerValue>,
}

/// Self-contained serialized value — mirrors `vex_graph::Value` but with all
/// strings resolved, so diff reports are portable and render-friendly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SerValue {
    Null,
    Bool(bool),
    Int(i64),
    Real(f64),
    Text(String),
    Enum(String),
    List(Vec<SerValue>),
    Typed { name: String, inner: Box<SerValue> },
}

/// A single semantic change between two models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Change {
    Added {
        identity: Identity,
        type_name: String,
    },
    Removed {
        identity: Identity,
        type_name: String,
    },
    Modified {
        identity: Identity,
        type_name: String,
        deltas: Vec<PropDelta>,
        layer: Layer,
    },
}

/// How we identified a given matched (or unmatched) node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Identity {
    GlobalId(String),
    StructuralHash(String),
    StepId(u64),
}

/// Aggregate report from a diff run.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiffReport {
    pub changes: Vec<Change>,
    pub summary: DiffSummary,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiffSummary {
    pub added: u32,
    pub removed: u32,
    pub modified: u32,
}

/// Compute a semantic diff between two IFC graphs.
///
/// `interner_a` and `interner_b` may be separate interner instances — this is
/// the common case since two models are parsed independently. The diff
/// resolves all interned strings internally.
pub fn diff(
    a: &IfcGraph,
    interner_a: &StringInterner,
    b: &IfcGraph,
    interner_b: &StringInterner,
    cfg: &HashConfig,
) -> DiffReport {
    let ha = hash_graph(a, interner_a, cfg);
    let hb = hash_graph(b, interner_b, cfg);

    // Build GlobalId indexes.
    let idx_by_guid_a = index_by_global_id(a);
    let idx_by_guid_b = index_by_global_id(b);

    // Build hash indexes.
    let mut by_hash_a: AHashMap<Hash256, NodeId> = AHashMap::with_capacity(a.node_count());
    let mut by_hash_b: AHashMap<Hash256, NodeId> = AHashMap::with_capacity(b.node_count());
    for (id, _) in &a.nodes {
        by_hash_a.insert(ha.per_node[&id], id);
    }
    for (id, _) in &b.nodes {
        by_hash_b.insert(hb.per_node[&id], id);
    }

    let mut matched_a: AHashSet<NodeId> = AHashSet::with_capacity(a.node_count());
    let mut matched_b: AHashSet<NodeId> = AHashSet::with_capacity(b.node_count());
    let mut changes: Vec<Change> = Vec::new();
    let mut summary = DiffSummary::default();

    // === Pass 1: match by GlobalId ===
    for (guid, &id_a) in &idx_by_guid_a {
        if let Some(&id_b) = idx_by_guid_b.get(guid) {
            matched_a.insert(id_a);
            matched_b.insert(id_b);
            if ha.per_node[&id_a] == hb.per_node[&id_b] {
                continue;
            }
            let node_a = &a.nodes[id_a];
            let node_b = &b.nodes[id_b];
            let deltas = diff_properties(node_a, interner_a, node_b, interner_b);
            let layer = if deltas.is_empty() {
                Layer::Relationship
            } else {
                Layer::Property
            };
            changes.push(Change::Modified {
                identity: Identity::GlobalId(guid.clone()),
                type_name: interner_b.resolve(node_b.type_name).to_string(),
                deltas,
                layer,
            });
            summary.modified += 1;
        }
    }

    for id in &matched_a {
        by_hash_a.remove(&ha.per_node[id]);
    }
    for id in &matched_b {
        by_hash_b.remove(&hb.per_node[id]);
    }

    // === Pass 2: match by exact structural hash ===
    let a_hashes: Vec<Hash256> = by_hash_a.keys().copied().collect();
    for h in a_hashes {
        if let Some(&id_b) = by_hash_b.get(&h) {
            let id_a = by_hash_a[&h];
            matched_a.insert(id_a);
            matched_b.insert(id_b);
            by_hash_a.remove(&h);
            by_hash_b.remove(&h);
        }
    }

    // === Pass 3: report unmatched ===
    for (id, node) in &a.nodes {
        if !matched_a.contains(&id) {
            changes.push(Change::Removed {
                identity: best_identity(node, ha.per_node[&id]),
                type_name: interner_a.resolve(node.type_name).to_string(),
            });
            summary.removed += 1;
        }
    }
    for (id, node) in &b.nodes {
        if !matched_b.contains(&id) {
            changes.push(Change::Added {
                identity: best_identity(node, hb.per_node[&id]),
                type_name: interner_b.resolve(node.type_name).to_string(),
            });
            summary.added += 1;
        }
    }

    changes.sort_by_key(change_sort_key);

    DiffReport { changes, summary }
}

fn index_by_global_id(g: &IfcGraph) -> AHashMap<String, NodeId> {
    let mut out = AHashMap::with_capacity(g.node_count());
    for (id, node) in &g.nodes {
        if let Some(gid) = &node.global_id {
            out.insert(gid.0.clone(), id);
        }
    }
    out
}

fn best_identity(node: &Node, hash: Hash256) -> Identity {
    if let Some(g) = &node.global_id {
        Identity::GlobalId(g.0.clone())
    } else if hash != Hash256::ZERO {
        Identity::StructuralHash(hash.to_hex())
    } else {
        Identity::StepId(node.step_id)
    }
}

fn diff_properties(a: &Node, ia: &StringInterner, b: &Node, ib: &StringInterner) -> Vec<PropDelta> {
    let mut map_a: BTreeMap<String, &Value> = BTreeMap::new();
    for (k, v) in &a.props {
        map_a.insert(ia.resolve(*k).to_string(), v);
    }
    let mut map_b: BTreeMap<String, &Value> = BTreeMap::new();
    for (k, v) in &b.props {
        map_b.insert(ib.resolve(*k).to_string(), v);
    }

    let mut all_keys: AHashSet<String> = AHashSet::new();
    for k in map_a.keys() {
        all_keys.insert(k.clone());
    }
    for k in map_b.keys() {
        all_keys.insert(k.clone());
    }
    let mut keys: Vec<String> = all_keys.into_iter().collect();
    keys.sort();

    let mut out = Vec::new();
    for k in keys {
        let va = map_a.get(&k).copied();
        let vb = map_b.get(&k).copied();
        match (va, vb) {
            (Some(x), Some(y)) => {
                let rx = resolve(x, ia);
                let ry = resolve(y, ib);
                if rx != ry {
                    out.push(PropDelta {
                        key: k,
                        before: Some(rx),
                        after: Some(ry),
                    });
                }
            }
            (Some(x), None) => out.push(PropDelta {
                key: k,
                before: Some(resolve(x, ia)),
                after: None,
            }),
            (None, Some(y)) => out.push(PropDelta {
                key: k,
                before: None,
                after: Some(resolve(y, ib)),
            }),
            (None, None) => unreachable!(),
        }
    }
    out
}

pub(crate) fn resolve(v: &Value, i: &StringInterner) -> SerValue {
    match v {
        Value::Null => SerValue::Null,
        Value::Bool(b) => SerValue::Bool(*b),
        Value::Int(n) => SerValue::Int(*n),
        Value::Real(x) => SerValue::Real(*x),
        Value::Text(s) => SerValue::Text(i.resolve(*s).to_string()),
        Value::Enum(s) => SerValue::Enum(i.resolve(*s).to_string()),
        Value::List(xs) => SerValue::List(xs.iter().map(|x| resolve(x, i)).collect()),
        Value::Typed { name, inner } => SerValue::Typed {
            name: i.resolve(*name).to_string(),
            inner: Box::new(resolve(inner, i)),
        },
    }
}

fn change_sort_key(c: &Change) -> (u8, String) {
    let (order, id) = match c {
        Change::Removed { identity, .. } => (0, identity_key(identity)),
        Change::Modified { identity, .. } => (1, identity_key(identity)),
        Change::Added { identity, .. } => (2, identity_key(identity)),
    };
    (order, id)
}

fn identity_key(id: &Identity) -> String {
    match id {
        Identity::GlobalId(s) => format!("G:{s}"),
        Identity::StructuralHash(s) => format!("H:{s}"),
        Identity::StepId(n) => format!("S:{n}"),
    }
}

/// Convenience renderer producing Git-style human-readable output.
pub fn render_text(report: &DiffReport) -> String {
    let mut out = String::new();
    for c in &report.changes {
        match c {
            Change::Added {
                identity,
                type_name,
            } => {
                let _ = writeln!(out, "+ {type_name} {}", identity_text(identity));
            }
            Change::Removed {
                identity,
                type_name,
            } => {
                let _ = writeln!(out, "- {type_name} {}", identity_text(identity));
            }
            Change::Modified {
                identity,
                type_name,
                deltas,
                layer,
            } => {
                let _ = writeln!(out, "~ {type_name} {} [{layer:?}]", identity_text(identity),);
                for d in deltas {
                    let _ = writeln!(out, "    {} : {:?} -> {:?}", d.key, d.before, d.after);
                }
            }
        }
    }
    let _ = writeln!(
        out,
        "\n{} added, {} removed, {} modified",
        report.summary.added, report.summary.removed, report.summary.modified
    );
    out
}

fn identity_text(id: &Identity) -> String {
    match id {
        Identity::GlobalId(s) => format!("GlobalId={s}"),
        Identity::StructuralHash(s) => format!("Hash={}", &s[..16.min(s.len())]),
        Identity::StepId(n) => format!("#{n}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;
    use vex_graph::GraphBuilder;
    use vex_ifc_parser::{ParseLimits, Parser};

    fn build(src: &str) -> (IfcGraph, StringInterner) {
        let i = StringInterner::new();
        let mut p = Parser::new(Cursor::new(src), ParseLimits::default());
        let g = GraphBuilder::build_from_parser(i.clone(), &mut p).expect("build");
        (g, i)
    }

    const BASE: &str = "\
ISO-10303-21;
HEADER; FILE_DESCRIPTION((''),'2;1'); FILE_NAME('','',(''),(''),'','',''); FILE_SCHEMA(('IFC4')); ENDSEC;
DATA;
#1 = IFCPROJECT('0YvctVUKr0kugbFTf53O9L',$,'Project',$,$,$,$,$,$);
#2 = IFCWALL('2O2Fr$t4X7Zf8NOew3FNr2',$,'Wall-1',$,$,$,$,$,.STANDARD.);
ENDSEC;
END-ISO-10303-21;
";

    #[test]
    fn no_changes_on_identical() {
        let (a, ia) = build(BASE);
        let (b, ib) = build(BASE);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.changes.len(), 0);
    }

    #[test]
    fn detects_property_change() {
        let (a, ia) = build(BASE);
        let mutated = BASE.replace("'Wall-1'", "'Wall-2'");
        let (b, ib) = build(&mutated);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.summary.modified, 1);
        assert_eq!(r.summary.added, 0);
        assert_eq!(r.summary.removed, 0);
    }

    #[test]
    fn detects_addition() {
        let (a, ia) = build(BASE);
        let added = BASE.replace(
            "ENDSEC;\nEND-ISO-10303-21;",
            "#3 = IFCSLAB('3O2Fr$t4X7Zf8NOew3FNr3',$,'Slab',$,$,$,$,$,.FLOOR.);\nENDSEC;\nEND-ISO-10303-21;",
        );
        let (b, ib) = build(&added);
        let r = diff(&a, &ia, &b, &ib, &HashConfig::default());
        assert_eq!(r.summary.added, 1);
        assert_eq!(r.summary.removed, 0);
    }
}
